version: '3.8'

services:
  app:
    image: gaddamnaveen192/dockerdemo:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Booksw?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Booksw
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
